// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

#nullable disable

namespace api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260407145333_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api.Products.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "https://picsum.photos/seed/product1/200/200",
                            Name = "Product 1",
                            Price = 11.49
                        },
                        new
                        {
                            Id = 2,
                            Image = "https://picsum.photos/seed/product2/200/200",
                            Name = "Product 2",
                            Price = 12.99
                        },
                        new
                        {
                            Id = 3,
                            Image = "https://picsum.photos/seed/product3/200/200",
                            Name = "Product 3",
                            Price = 14.49
                        },
                        new
                        {
                            Id = 4,
                            Image = "https://picsum.photos/seed/product4/200/200",
                            Name = "Product 4",
                            Price = 15.99
                        },
                        new
                        {
                            Id = 5,
                            Image = "https://picsum.photos/seed/product5/200/200",
                            Name = "Product 5",
                            Price = 17.489999999999998
                        },
                        new
                        {
                            Id = 6,
                            Image = "https://picsum.photos/seed/product6/200/200",
                            Name = "Product 6",
                            Price = 18.989999999999998
                        },
                        new
                        {
                            Id = 7,
                            Image = "https://picsum.photos/seed/product7/200/200",
                            Name = "Product 7",
                            Price = 20.489999999999998
                        },
                        new
                        {
                            Id = 8,
                            Image = "https://picsum.photos/seed/product8/200/200",
                            Name = "Product 8",
                            Price = 21.989999999999998
                        },
                        new
                        {
                            Id = 9,
                            Image = "https://picsum.photos/seed/product9/200/200",
                            Name = "Product 9",
                            Price = 23.489999999999998
                        },
                        new
                        {
                            Id = 10,
                            Image = "https://picsum.photos/seed/product10/200/200",
                            Name = "Product 10",
                            Price = 24.989999999999998
                        },
                        new
                        {
                            Id = 11,
                            Image = "https://picsum.photos/seed/product11/200/200",
                            Name = "Product 11",
                            Price = 26.489999999999998
                        },
                        new
                        {
                            Id = 12,
                            Image = "https://picsum.photos/seed/product12/200/200",
                            Name = "Product 12",
                            Price = 27.989999999999998
                        },
                        new
                        {
                            Id = 13,
                            Image = "https://picsum.photos/seed/product13/200/200",
                            Name = "Product 13",
                            Price = 29.489999999999998
                        },
                        new
                        {
                            Id = 14,
                            Image = "https://picsum.photos/seed/product14/200/200",
                            Name = "Product 14",
                            Price = 30.989999999999998
                        },
                        new
                        {
                            Id = 15,
                            Image = "https://picsum.photos/seed/product15/200/200",
                            Name = "Product 15",
                            Price = 32.490000000000002
                        },
                        new
                        {
                            Id = 16,
                            Image = "https://picsum.photos/seed/product16/200/200",
                            Name = "Product 16",
                            Price = 33.990000000000002
                        },
                        new
                        {
                            Id = 17,
                            Image = "https://picsum.photos/seed/product17/200/200",
                            Name = "Product 17",
                            Price = 35.490000000000002
                        },
                        new
                        {
                            Id = 18,
                            Image = "https://picsum.photos/seed/product18/200/200",
                            Name = "Product 18",
                            Price = 36.990000000000002
                        },
                        new
                        {
                            Id = 19,
                            Image = "https://picsum.photos/seed/product19/200/200",
                            Name = "Product 19",
                            Price = 38.490000000000002
                        },
                        new
                        {
                            Id = 20,
                            Image = "https://picsum.photos/seed/product20/200/200",
                            Name = "Product 20",
                            Price = 39.990000000000002
                        },
                        new
                        {
                            Id = 21,
                            Image = "https://picsum.photos/seed/product21/200/200",
                            Name = "Product 21",
                            Price = 41.490000000000002
                        },
                        new
                        {
                            Id = 22,
                            Image = "https://picsum.photos/seed/product22/200/200",
                            Name = "Product 22",
                            Price = 42.990000000000002
                        },
                        new
                        {
                            Id = 23,
                            Image = "https://picsum.photos/seed/product23/200/200",
                            Name = "Product 23",
                            Price = 44.490000000000002
                        },
                        new
                        {
                            Id = 24,
                            Image = "https://picsum.photos/seed/product24/200/200",
                            Name = "Product 24",
                            Price = 45.990000000000002
                        },
                        new
                        {
                            Id = 25,
                            Image = "https://picsum.photos/seed/product25/200/200",
                            Name = "Product 25",
                            Price = 47.490000000000002
                        },
                        new
                        {
                            Id = 26,
                            Image = "https://picsum.photos/seed/product26/200/200",
                            Name = "Product 26",
                            Price = 48.990000000000002
                        },
                        new
                        {
                            Id = 27,
                            Image = "https://picsum.photos/seed/product27/200/200",
                            Name = "Product 27",
                            Price = 50.490000000000002
                        },
                        new
                        {
                            Id = 28,
                            Image = "https://picsum.photos/seed/product28/200/200",
                            Name = "Product 28",
                            Price = 51.990000000000002
                        },
                        new
                        {
                            Id = 29,
                            Image = "https://picsum.photos/seed/product29/200/200",
                            Name = "Product 29",
                            Price = 53.490000000000002
                        },
                        new
                        {
                            Id = 30,
                            Image = "https://picsum.photos/seed/product30/200/200",
                            Name = "Product 30",
                            Price = 54.990000000000002
                        },
                        new
                        {
                            Id = 31,
                            Image = "https://picsum.photos/seed/product31/200/200",
                            Name = "Product 31",
                            Price = 56.490000000000002
                        },
                        new
                        {
                            Id = 32,
                            Image = "https://picsum.photos/seed/product32/200/200",
                            Name = "Product 32",
                            Price = 57.990000000000002
                        },
                        new
                        {
                            Id = 33,
                            Image = "https://picsum.photos/seed/product33/200/200",
                            Name = "Product 33",
                            Price = 59.490000000000002
                        },
                        new
                        {
                            Id = 34,
                            Image = "https://picsum.photos/seed/product34/200/200",
                            Name = "Product 34",
                            Price = 60.990000000000002
                        },
                        new
                        {
                            Id = 35,
                            Image = "https://picsum.photos/seed/product35/200/200",
                            Name = "Product 35",
                            Price = 62.490000000000002
                        },
                        new
                        {
                            Id = 36,
                            Image = "https://picsum.photos/seed/product36/200/200",
                            Name = "Product 36",
                            Price = 63.990000000000002
                        },
                        new
                        {
                            Id = 37,
                            Image = "https://picsum.photos/seed/product37/200/200",
                            Name = "Product 37",
                            Price = 65.489999999999995
                        },
                        new
                        {
                            Id = 38,
                            Image = "https://picsum.photos/seed/product38/200/200",
                            Name = "Product 38",
                            Price = 66.989999999999995
                        },
                        new
                        {
                            Id = 39,
                            Image = "https://picsum.photos/seed/product39/200/200",
                            Name = "Product 39",
                            Price = 68.489999999999995
                        },
                        new
                        {
                            Id = 40,
                            Image = "https://picsum.photos/seed/product40/200/200",
                            Name = "Product 40",
                            Price = 69.989999999999995
                        },
                        new
                        {
                            Id = 41,
                            Image = "https://picsum.photos/seed/product41/200/200",
                            Name = "Product 41",
                            Price = 71.489999999999995
                        },
                        new
                        {
                            Id = 42,
                            Image = "https://picsum.photos/seed/product42/200/200",
                            Name = "Product 42",
                            Price = 72.989999999999995
                        },
                        new
                        {
                            Id = 43,
                            Image = "https://picsum.photos/seed/product43/200/200",
                            Name = "Product 43",
                            Price = 74.489999999999995
                        },
                        new
                        {
                            Id = 44,
                            Image = "https://picsum.photos/seed/product44/200/200",
                            Name = "Product 44",
                            Price = 75.989999999999995
                        },
                        new
                        {
                            Id = 45,
                            Image = "https://picsum.photos/seed/product45/200/200",
                            Name = "Product 45",
                            Price = 77.489999999999995
                        },
                        new
                        {
                            Id = 46,
                            Image = "https://picsum.photos/seed/product46/200/200",
                            Name = "Product 46",
                            Price = 78.989999999999995
                        },
                        new
                        {
                            Id = 47,
                            Image = "https://picsum.photos/seed/product47/200/200",
                            Name = "Product 47",
                            Price = 80.489999999999995
                        },
                        new
                        {
                            Id = 48,
                            Image = "https://picsum.photos/seed/product48/200/200",
                            Name = "Product 48",
                            Price = 81.989999999999995
                        },
                        new
                        {
                            Id = 49,
                            Image = "https://picsum.photos/seed/product49/200/200",
                            Name = "Product 49",
                            Price = 83.489999999999995
                        },
                        new
                        {
                            Id = 50,
                            Image = "https://picsum.photos/seed/product50/200/200",
                            Name = "Product 50",
                            Price = 84.989999999999995
                        },
                        new
                        {
                            Id = 51,
                            Image = "https://picsum.photos/seed/product51/200/200",
                            Name = "Product 51",
                            Price = 86.489999999999995
                        },
                        new
                        {
                            Id = 52,
                            Image = "https://picsum.photos/seed/product52/200/200",
                            Name = "Product 52",
                            Price = 87.989999999999995
                        },
                        new
                        {
                            Id = 53,
                            Image = "https://picsum.photos/seed/product53/200/200",
                            Name = "Product 53",
                            Price = 89.489999999999995
                        },
                        new
                        {
                            Id = 54,
                            Image = "https://picsum.photos/seed/product54/200/200",
                            Name = "Product 54",
                            Price = 90.989999999999995
                        },
                        new
                        {
                            Id = 55,
                            Image = "https://picsum.photos/seed/product55/200/200",
                            Name = "Product 55",
                            Price = 92.489999999999995
                        },
                        new
                        {
                            Id = 56,
                            Image = "https://picsum.photos/seed/product56/200/200",
                            Name = "Product 56",
                            Price = 93.989999999999995
                        },
                        new
                        {
                            Id = 57,
                            Image = "https://picsum.photos/seed/product57/200/200",
                            Name = "Product 57",
                            Price = 95.489999999999995
                        },
                        new
                        {
                            Id = 58,
                            Image = "https://picsum.photos/seed/product58/200/200",
                            Name = "Product 58",
                            Price = 96.989999999999995
                        },
                        new
                        {
                            Id = 59,
                            Image = "https://picsum.photos/seed/product59/200/200",
                            Name = "Product 59",
                            Price = 98.489999999999995
                        },
                        new
                        {
                            Id = 60,
                            Image = "https://picsum.photos/seed/product60/200/200",
                            Name = "Product 60",
                            Price = 99.989999999999995
                        },
                        new
                        {
                            Id = 61,
                            Image = "https://picsum.photos/seed/product61/200/200",
                            Name = "Product 61",
                            Price = 101.48999999999999
                        },
                        new
                        {
                            Id = 62,
                            Image = "https://picsum.photos/seed/product62/200/200",
                            Name = "Product 62",
                            Price = 102.98999999999999
                        },
                        new
                        {
                            Id = 63,
                            Image = "https://picsum.photos/seed/product63/200/200",
                            Name = "Product 63",
                            Price = 104.48999999999999
                        },
                        new
                        {
                            Id = 64,
                            Image = "https://picsum.photos/seed/product64/200/200",
                            Name = "Product 64",
                            Price = 105.98999999999999
                        },
                        new
                        {
                            Id = 65,
                            Image = "https://picsum.photos/seed/product65/200/200",
                            Name = "Product 65",
                            Price = 107.48999999999999
                        },
                        new
                        {
                            Id = 66,
                            Image = "https://picsum.photos/seed/product66/200/200",
                            Name = "Product 66",
                            Price = 108.98999999999999
                        },
                        new
                        {
                            Id = 67,
                            Image = "https://picsum.photos/seed/product67/200/200",
                            Name = "Product 67",
                            Price = 110.48999999999999
                        },
                        new
                        {
                            Id = 68,
                            Image = "https://picsum.photos/seed/product68/200/200",
                            Name = "Product 68",
                            Price = 111.98999999999999
                        },
                        new
                        {
                            Id = 69,
                            Image = "https://picsum.photos/seed/product69/200/200",
                            Name = "Product 69",
                            Price = 113.48999999999999
                        },
                        new
                        {
                            Id = 70,
                            Image = "https://picsum.photos/seed/product70/200/200",
                            Name = "Product 70",
                            Price = 114.98999999999999
                        },
                        new
                        {
                            Id = 71,
                            Image = "https://picsum.photos/seed/product71/200/200",
                            Name = "Product 71",
                            Price = 116.48999999999999
                        },
                        new
                        {
                            Id = 72,
                            Image = "https://picsum.photos/seed/product72/200/200",
                            Name = "Product 72",
                            Price = 117.98999999999999
                        },
                        new
                        {
                            Id = 73,
                            Image = "https://picsum.photos/seed/product73/200/200",
                            Name = "Product 73",
                            Price = 119.48999999999999
                        },
                        new
                        {
                            Id = 74,
                            Image = "https://picsum.photos/seed/product74/200/200",
                            Name = "Product 74",
                            Price = 120.98999999999999
                        },
                        new
                        {
                            Id = 75,
                            Image = "https://picsum.photos/seed/product75/200/200",
                            Name = "Product 75",
                            Price = 122.48999999999999
                        },
                        new
                        {
                            Id = 76,
                            Image = "https://picsum.photos/seed/product76/200/200",
                            Name = "Product 76",
                            Price = 123.98999999999999
                        },
                        new
                        {
                            Id = 77,
                            Image = "https://picsum.photos/seed/product77/200/200",
                            Name = "Product 77",
                            Price = 125.48999999999999
                        },
                        new
                        {
                            Id = 78,
                            Image = "https://picsum.photos/seed/product78/200/200",
                            Name = "Product 78",
                            Price = 126.98999999999999
                        },
                        new
                        {
                            Id = 79,
                            Image = "https://picsum.photos/seed/product79/200/200",
                            Name = "Product 79",
                            Price = 128.49000000000001
                        },
                        new
                        {
                            Id = 80,
                            Image = "https://picsum.photos/seed/product80/200/200",
                            Name = "Product 80",
                            Price = 129.99000000000001
                        },
                        new
                        {
                            Id = 81,
                            Image = "https://picsum.photos/seed/product81/200/200",
                            Name = "Product 81",
                            Price = 131.49000000000001
                        },
                        new
                        {
                            Id = 82,
                            Image = "https://picsum.photos/seed/product82/200/200",
                            Name = "Product 82",
                            Price = 132.99000000000001
                        },
                        new
                        {
                            Id = 83,
                            Image = "https://picsum.photos/seed/product83/200/200",
                            Name = "Product 83",
                            Price = 134.49000000000001
                        },
                        new
                        {
                            Id = 84,
                            Image = "https://picsum.photos/seed/product84/200/200",
                            Name = "Product 84",
                            Price = 135.99000000000001
                        },
                        new
                        {
                            Id = 85,
                            Image = "https://picsum.photos/seed/product85/200/200",
                            Name = "Product 85",
                            Price = 137.49000000000001
                        },
                        new
                        {
                            Id = 86,
                            Image = "https://picsum.photos/seed/product86/200/200",
                            Name = "Product 86",
                            Price = 138.99000000000001
                        },
                        new
                        {
                            Id = 87,
                            Image = "https://picsum.photos/seed/product87/200/200",
                            Name = "Product 87",
                            Price = 140.49000000000001
                        },
                        new
                        {
                            Id = 88,
                            Image = "https://picsum.photos/seed/product88/200/200",
                            Name = "Product 88",
                            Price = 141.99000000000001
                        },
                        new
                        {
                            Id = 89,
                            Image = "https://picsum.photos/seed/product89/200/200",
                            Name = "Product 89",
                            Price = 143.49000000000001
                        },
                        new
                        {
                            Id = 90,
                            Image = "https://picsum.photos/seed/product90/200/200",
                            Name = "Product 90",
                            Price = 144.99000000000001
                        },
                        new
                        {
                            Id = 91,
                            Image = "https://picsum.photos/seed/product91/200/200",
                            Name = "Product 91",
                            Price = 146.49000000000001
                        },
                        new
                        {
                            Id = 92,
                            Image = "https://picsum.photos/seed/product92/200/200",
                            Name = "Product 92",
                            Price = 147.99000000000001
                        },
                        new
                        {
                            Id = 93,
                            Image = "https://picsum.photos/seed/product93/200/200",
                            Name = "Product 93",
                            Price = 149.49000000000001
                        },
                        new
                        {
                            Id = 94,
                            Image = "https://picsum.photos/seed/product94/200/200",
                            Name = "Product 94",
                            Price = 150.99000000000001
                        },
                        new
                        {
                            Id = 95,
                            Image = "https://picsum.photos/seed/product95/200/200",
                            Name = "Product 95",
                            Price = 152.49000000000001
                        },
                        new
                        {
                            Id = 96,
                            Image = "https://picsum.photos/seed/product96/200/200",
                            Name = "Product 96",
                            Price = 153.99000000000001
                        },
                        new
                        {
                            Id = 97,
                            Image = "https://picsum.photos/seed/product97/200/200",
                            Name = "Product 97",
                            Price = 155.49000000000001
                        },
                        new
                        {
                            Id = 98,
                            Image = "https://picsum.photos/seed/product98/200/200",
                            Name = "Product 98",
                            Price = 156.99000000000001
                        },
                        new
                        {
                            Id = 99,
                            Image = "https://picsum.photos/seed/product99/200/200",
                            Name = "Product 99",
                            Price = 158.49000000000001
                        },
                        new
                        {
                            Id = 100,
                            Image = "https://picsum.photos/seed/product100/200/200",
                            Name = "Product 100",
                            Price = 159.99000000000001
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
