# inventory.ini - Target servers for Docker installation

[docker_hosts]
server1 ansible_host=165.22.252.66

[docker_hosts:vars]
ansible_user=root
ansible_ssh_private_key_file=~/.ssh/id_rsa

app_dir=/root/myapp # Directory on target server to store docker-compose.yml

